name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        houdini-version:
          - "20.5"  # Python 3.11
          - "21.0"  # Python 3.11

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      # Unit Tests

      - name: Install unit test dependencies
        run: | 
          python3 -m pip install --upgrade pip
          python3 -m pip install --group deps --group github

      # Run static analysis tox tests
      - name: Test with tox (static)
        run: tox -m static

      # Run unit tests with tox
      - name: Test with tox (tests)
        run: tox -m test

      # Integration tests

      - name: Install integration test dependencies
        uses: ./
        with:
          packages: "pytest-sugar,pytest-subprocess"
          files: "tests/data/requirements.txt,tests/data/other.txt"
          groups: "deps,test_install_deps"
          projects: "https://github.com/captainhammy/you-can-call-me-houdini.git"

      - name: Test resolve
        run: rez env pytest_sugar pytest_subprocess pytest_asyncio pytest_ruff pytest_home tomlkit markdown-pytest you_can_call_me_houdini-- echo "resolve successful"
        shell: bash
